name: Master deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6
        with:
          heroku_api_key: ${{secrets.HEROKU_DEV_API_KEY}}
          heroku_app_name: "vladivostok"
          heroku_email: "acherepanov@strelka-kb.com"
          usedocker: true
